name: CI Pipeline for GuestService

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Cache .NET dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-guestservice-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-guestservice-nuget-

      - name: Restore dependencies
        run: dotnet restore ./GuestService/GuestService.csproj

      - name: Clean build directory
        run: dotnet clean ./GuestService/GuestService.csproj

      - name: Build the project
        run: dotnet build ./GuestService/GuestService.csproj --configuration Release --no-restore

      - name: Restore dependencies for tests
        run: dotnet restore ./GuestService.Tests/GuestService.Tests.csproj

      - name: Run unit tests with diagnostics
        run: dotnet test 

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/guestservice:latest -f ./Dockerfile .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/guestservice:latest
